# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Celeste' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Celeste
	pod 'Hero'
  pod 'OTPTextField'
  pod 'SwiftyGif'
  pod 'FSCalendar'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'CodableFirebase'
  pod 'Kingfisher', '~> 5.0'
  pod 'lottie-ios'
  pod 'SPStorkController'
  pod 'TextFieldEffects'
  pod 'IQKeyboardManager'
  pod 'DropDown'
  pod 'SPAlert'
  pod 'FSPagerView'

  target 'CelesteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CelesteUITests' do
    # Pods for testing
  end

end
